### ISSUE TITLE
Failed to extract deps-macos-10.4.1.tar.gz

### ISSUE THREAD

**Issue by alanshaw** [ipfs/dev-team-enablement#145]
<img width="509" alt="screenshot 2018-09-28 at 17 09 35" src="https://user-images.githubusercontent.com/152863/46220213-561f9100-c341-11e8-8bc4-235c53039f14.png">

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-1600/3/pipeline/61

**Comment by alanshaw** [comment]
Now windows:

```
Failed to extract deps-windows-10.11.0.tar.gz
```

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/PR-854/12/pipeline

**Comment by vmx** [comment]
On Windows this is due to running out of disk space, I've opened https://github.com/ipfs/testing/issues/158 for that.

**Comment by vmx** [comment]
Happened again: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/PR-872/9/pipeline/363

```
12:32:25 [macos test:browser] java.nio.file.FileSystemException: /var/jenkins/workspace/IPFS_js-ipfs-api_PR-872-QLAFZL7AUONHCDOGBAQD6D3AODP3I2P4VGH4KWVGD3YKFL4FHGZA@2/node_modules/xregexp/tests: No space left on device
```
