### ISSUE TITLE
Windows worker is out of diskspace

### ISSUE THREAD

**Issue by vmx** [ipfs/dev-team-enablement#158]
## Which Project is this about?

js-ipfs

## Provide a link to a example run where it went wrong

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-1626/12/pipeline/
https://ci.ipfs.team/job/IPFS/job/js-ipfs/job/PR-1626/12/consoleFull

```
11:03:33 [windows:8.12.0 test:node] ERROR: Execution failed
11:03:33 [windows:8.12.0 test:node] java.io.IOException: There is not enough space on the disk
```

Implementing https://ci.ipfs.team/job/IPFS/job/js-ipfs/job/PR-1626/12/consoleFull should help preventing this problem.

## Which platform did the issue happen on?

Windows

**Comment by VictorBjelkholm** [comment]
We should hit this way less now

https://github.com/ipfs/jenkins/commit/ab66c5f767c11eb799fca89dfa3601107cb8630b
