### ISSUE TITLE
Webui CI job fails to publish dnslink update

### ISSUE THREAD

**Issue by olizilla** [ipfs/dev-team-enablement#162]
## Which Project is this about?

https://github.com/ipfs-shipyard/ipfs-webui

## Provide a link to a example run where it went wrong

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipfs-webui/detail/master/12/pipeline

**Comment by olizilla** [comment]
The last succesful dnslink update to https://webui.ipfs.io was Oct 4th!

**Comment by olizilla** [comment]
@VictorBjelkholm we're now getting a 404 error on the dnssimple update step

```console
./dnslink-dnsimple webui.ipfs.io /ipfs/QmNUuPtET3zmnSv5qE6paaW4XRuNPjWyWPZpxNqYVw41Hg _dnslink
error in createRecord: POST https://api.dnsimple.com/v2/zones/webui.ipfs.io/records: 404 Not Found
script returned exit code 1
```

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipfs-webui/detail/master/24/pipeline/#step-74-log-3

**Comment by olizilla** [comment]
@ipfs/infrastructure I'd like to re-enable deployments to https://webui.ipfs.io from Jenkins. Can you help?

**Comment by VictorBjelkholm** [comment]
Permissions was missing for the right user in DNSimple. Corrected and now the build should be fine again. Sorry for that.
